theme:
  name: material
  favicon: favicon.ico
  logo: images/cirrus_logo_white-Transparent-Background.png
  palette:
    primary: blue
    accent:  blue
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github

extra_css:  [stylesheets/cirrus.css]

site_name: Cirrus User Documentation
repo_url: https://github.com/EPCCed/cirrus-docs
repo_name: EPCCed/cirrus-docs
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EPCCed
  analytics:
    provider: google
    property: 
  analytics:
    provider: google
    property: G-3T9RVR5FTP

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - "Overview": index.md
  - "Migration to Cirrus EX4000":
    - "Overview": migration-2025/index.md
    - "Account migration": migration-2025/account-migration.md
    - "Data migration": migration-2025/data-migration.md
    - "Cirrus EX4000 differences": migration-2025/cirrus-differences.md
  - "User Guide":
    - "Introduction": user-guide/introduction.md
    - "Hardware": user-guide/hardware.md
    - "Connecting to Cirrus": user-guide/connecting.md
    - "Data Management and Transfer": user-guide/data.md
    - "File and Resource Management": user-guide/resource_management.md
    - "Application Development Environment": user-guide/development.md
    - "Running Jobs on Cirrus": user-guide/batch.md
    - "Singularity Containers": user-guide/singularity.md
    - "Using Python": user-guide/python.md
    - "Solid state storage": user-guide/solidstate.md
  - "Software Applications":
    - "CASTEP": software-packages/castep.md
    - "CP2K": software-packages/cp2k.md
    - "GROMACS": software-packages/gromacs.md
    - "HELYX&reg;": software-packages/helyx.md
    - "LAMMPS": software-packages/lammps.md
    - "OpenFOAM": software-packages/openfoam.md
    - "ORCA": software-packages/orca.md
    - "Quantum Espresso (QE)": software-packages/qe.md
    - "VASP": software-packages/vasp.md
  - "Software Libraries":
    - "Intel MKL: BLAS, LAPACK, ScaLAPACK": software-libraries/intel_mkl.md
    - "HDF5": software-libraries/hdf5.md
  - "Software Tools":
    - "Linaro Forge": software-tools/forge.md
    - "Profiling using Scalasca": software-tools/scalasca.md
    - "Intel VTune": software-tools/intel-vtune.md
  - "References and further reading": user-guide/reading.md
